-- AlterTable
ALTER TABLE "Product" ADD COLUMN     "price" DOUBLE PRECISION,
ALTER COLUMN "closedLength" SET DATA TYPE TEXT,
ALTER COLUMN "closedWidth" SET DATA TYPE TEXT,
ALTER COLUMN "primaryPackageWeight" SET DATA TYPE TEXT,
ALTER COLUMN "closedDepth" SET DATA TYPE TEXT;
